title: 'imlokisenpai.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: "/console"
url: "https://imlokisenpai.github.io"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: dark

footer: 'NOTHING <a href="https://imlokisenpai.github.io">HERE</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-spaceship

jekyll_admin:
  hidden_links:
    - posts
  homepage: "pages"
